# Use your RPC variable key from .env
rpc_url_key = "POLYGON_RPC_URL"

[dexes]
# ✅ Uniswap V2 Router on Polygon
uniswap_v2 = "0x1b02da8cb0d097eb8d57a175b88c7d8b47997506"

# ✅ QuickSwap V2 Router
quickswap_v2 = "0xa5E0829CaCEd8fFDD4De3c43696c57F7D7A678ff"

[tokens]
# ✅ Wrapped ETH (WETH) on Polygon
weth = "0x7ceb23fd6bc0add59e62ac25578270cff1b9f619"

# ✅ USDC on Polygon (6 decimals)
usdc = "0x2791bca1f2de4661ed88a30c99a7a9449aa84174"

[arbitrage]
# Start small to avoid revert (0.01 WETH ≈ ~$20)
trade_amount_weth = 0.1

# Only log trades that show >$1 profit
profit_threshold_usdc = 1.0

# How often to check for opportunities (in seconds)
polling_interval_seconds = 15
